version: '3.8'
name: 'apis_db'
volumes:
  apis_db_data:
    driver: local
services:
  apis_db:
    container_name: apis_db
    image: postgres:latest
    restart: always
    env_file:
        - path: .env
          required: false
    ports:
      - 5432:5432
    volumes:
      - apis_db_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
