[tool.ruff]
target-version = "py312"
lint.select = [
    "ALL", # include all the rules, including new ones
]
lint.ignore = [
    #### specific rules
    "CPY001",   # Prevent warning about copyright
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",
    "E402",   # false positives for local imports
    "E501",   # line too long
    "TRY003", # external messages in exceptions are too verbose
    "TD002",
    "TD003",
    "FIX002", # too verbose descriptions of todos
    "COM812",
    "PLR0913", # Disables warning on too many method params / args
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101", # asserts allowed in tests
    "S105", # Allow hardcoded passwords in test files
    "S106", # Allow hardcoded passwords in test files
    "PLR2004", # Allow magic numbers in test files
]
