erDiagram
    users {
        INT user_id PK
        TEXT username
        TEXT password
    }
    users ||--o{ sessions : have
    sessions {
        INT session_id PK
        TIMESTAMPTZ session_start
        INT user_id FK
    }
    users ||--o{ apiaries : have
    apiaries {
        INT apiary_id PK
        TEXT name
        TEXT location
        TEXT user_id FK
    }
    apiaries ||--o{ hives : have
    hives {
        INT hive_id PK
        TEXT name
        INT apiary_id FK
    }
    hives ||--o| colonies : have
    colonies {
        INT colony_id PK
        INT hive_id FK
    }
    colonies ||--o{ queens : have
    queens {
        INT queen_id PK
        ENUM colour
        BOOL clipped
        INT colony_id FK
    }
    colonies ||--o{ inspections : have
    inspections {
        INT inspection_id PK
        TIMESTAMPTZ inspection_timestamp
        INT colony_id FK
    }
    inspections ||--o{ observations : have
    observations {
        INT observation_id PK
        BOOL queenright
        INT queen_cells
        BOOL bias
        INT brood_frames
        INT store_frames
        BOOL chalk_brood
        BOOL foul_brood
        INT varroa_count
        INT temper
        TEXT notes
        INT inspection_id FK
    }
    inspections ||--o{ actions : have
    actions {
        INT action_id PK
        TEXT notes
        INT inspection_id FK
    }
