name: Run pytest
on: [pull_request]
jobs:
  run-pytest:
    name: Run pytest on codebase
    runs-on: ubuntu-latest
    steps:
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11.12'
        - name: Check out repo
          uses: actions/checkout@v4
        - name: Create .env from repository variables
          run: |
              cat <<EOF > .env
              POSTGRES_USER=${{ vars.POSTGRES_USER }}
              POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}
              POSTGRES_DB=${{ vars.POSTGRES_DB }}
              POSTGRES_HOST=${{ vars.POSTGRES_HOST }}
              POSTGRES_PORT=${{ vars.POSTGRES_PORT }}
              EOF
        - name: Set up Docker Compose
          uses: docker/setup-compose-action@v1
        - name: Upgrade pip
          run: python -m pip install --upgrade pip setuptools wheel
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Install dev dependencies
          run: pip install -r dev-requirements.txt
        - name: Run docker compose
          run: docker compose up -d
        - name: Run pytest
          run: python3 -m pytest -vvv
