name: Run pytest
on: [pull_request]
jobs:
  run-pytest:
    name: Run pytest on codebase
    runs-on: ubuntu-latest
    steps:
        - name: Check out repo
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11.12'
        - name: Set up Docker Compose
          uses: docker/setup-compose-action@v1
          env:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_DB: apis_database
        - name: Upgrade pip
          run: python -m pip install --upgrade pip setuptools wheel
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Install dev dependencies
          run: pip install -r dev-requirements.txt
        - name: Run docker compose
          run: docker compose up
        - name: Run pytest
          run: python3 -m pytest -vvv
