name: Run pytest and coverage
on:
    pull_request:
        branches:
            - main
permissions:
    checks: write
    contents: write
jobs:
    pytest-coverage:
        name: Run Pytest and Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.11.12"
                cache: 'pip'
            - name: Install dependencies
              run: python -m pip install --upgrade pip setuptools wheel
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r dev-requirements.txt
            - name: Run tests
              run: |
                python coverage run -m pytest -vvvspP
                coverage report -m
